baseURL: 'https://sazidthe1.github.io/'
languageCode: en-us
title: Sazid
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: search
      name: Search
      url: /search
      weight: 40
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 50

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Sazid"
    subtitle: Hi 👋! I'm Sazid, .
    imageUrl: "home/content/images/sazid.jpeg"
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "twitter"
      url: "https://twitter.com/sazidthe1"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/sazidthe1"
    - name: "github"
      url: "https://github.com/sazidthe1"
    - name: "hashnode"
      url: "https://sazidthe1.hashnode.dev/"
    - name: "bio"
      url: "https://bio.link/sazidthe1"
    

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true